### ISSUE TITLE
where to store definitive infographiq templates & functions?

### ISSUE THREAD

**Issue by bbest** [noaa-onms/onmsR#3]
Let's consider one place, probably [infographiq](https://github.com/marinebon/infographiq), for a set of functions and templates using Github Releases (ie versions of product) with potential for backward compatibility, multiple output types (Rmd website, Rmd standalone page, Drupal Module, HTML standalone page, ...).

## Present: Jumble of Repos

Presently the interactive infographics core files and functions live in too many locations:

* [infographiq](https://github.com/marinebon/infographiq)
  Original R package with documented functions and files to generate an interactive infographic website.
  - Definitive JS and CSS should live here, managed as Github Releases associated with version numbers.
* [info-demo](https://github.com/marinebon/info-demo)
  Quick demonstration of how to implement an interactive infographic website. ToDo: Migrate this content to a Vignette and template within the infographiq package.
  * [drupal-module](https://github.com/marinebon/info-demo/tree/master/drupal-module)
* [nms4r](https://github.com/marinebon/nms4r)
  National Marine Sanctuaries focused R package for reading, summarizing and plotting relevant datasets (ERDDAP oceano, CalCOFI fisheries, MARINe rocky intertidal) that also blends with functions for creating a more advanced interactive infographic website with glossary

Instances:
* [cinms](https://github.com/marinebon/cinms)
  Most advanced instance of interactive infographic website with:
  1. Glossary
  2. 
* [mbnms](https://github.com/marinebon/mbnms)
  * OLD: [info-mb](https://github.com/marinebon/info-mb)
* [fk-esr-info](https://github.com/marinebon/fk-esr-info)
  * OLD: [info-fk](https://github.com/marinebon/info-fk): original using Rmd
  * [fk-iea](https://github.com/marinebon/fk-iea): Tylar using Python, Jekyll
  * [fk-iea_tmp](https://github.com/marinebon/fk-iea_tmp): BB using Distill

## Future: Consolidated Framework — Single instances using core infographiq R package

1. What is common across repos that we could consolidate?
2. Can core files be pulled over the web **remotely**? Commonly, Content Delivery Network (CDN) versions of JS and CSS files are pulled over the web. For example, for a quick start to [Bootstrap v4.5](https://getbootstrap.com/docs/4.5/getting-started/introduction/), the following HTML lines include these core files:
```html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>
```
3. What needs to be available **locally** to the instance, and possibly updatable with `infographiq::update_website()` or similar?

**Comment by 7yl4r** [comment]
This is something I have been craving so that I can build on top of the infographics work and push improvements back upstream. I think it makes sense to have two repos: A) the package of core files that makes everything work (infographiq) and B) a boilerplate of minimal example locally-required files to be forked and used as a template for new infographic sites (info-demo or similar).

**Comment by bbest** [comment]
Ok, I'm liking this architecture. I think we should put this into the **infographiq** documentation.

- **marinebon/**
  Marine Biodiversity Observation Network (IOOS/NOAA/NASA) support
  - [**infographiqJS**](https://marinebon.org/infographiqJS): core JS-only (without R or other JS libraries)
    * _**templates**_: [infographiq_example.zip](https://github.com/marinebon/infographiqJS/blob/main/infographiq_example.zip) (HTML/JS only)
  - [**infographiqR**](https://marinebon.org/infographiqR): R helper functions 
    * _**templates**_: TODO: marinebon/infographiqR#64
  - [**infographiq**](https://marinebon.org/infographiq): documentation showing all the interoperable elements and scenarios
- **noaa-onms/**:
  NOAA's Office of National Marine Sanctuary
  - [**onmsR**](https://noaa-onms.github.io/onmsR): helper functions for dataset-specific wrangling and visualization
  - [**cinms**](https://noaa-onms.github.io/cinms): _**instance**_ of infographiqR website for Channel Islands
  - [**ocnms**](https://noaa-onms.github.io/ocnms): _**instance**_ of infographiqR website for Olympic Coast
  - [**sanctsound**](https://noaa-onms.github.io/ocnms): _**instance**_ of infographiqR website for Sanctuaries & Sound
- **noaa-iea/**
  NOAA's Integrated Ecosystem Assessment program
  - [**plotJS-extra**](https://github.com/noaa-iea/plotJS-extra): extra JS plot with IEA style
  - [**fk-esr-info**](https://noaa-iea.github.io/fk-esr-info/infographic.html):_**instance**_ of infographiqJS website

This hierarchy was also visualized by Jenn:

![image.png](https://images.zenhubusercontent.com/53c976bbe6799ebe48001049/74724b08-9608-4499-ab9f-7fed14182c74)

**Comment by bbest** [comment]
Closing since moved to marinebon/infographiq#4
